.PHONY: all build clean

all: build clean

build: sw01 sw02 sw04 sw05 sw07 sw08

sw01:
	pdflatex notes_sw01.tex
	pdflatex notes_sw01.tex
	pdflatex notes_sw01.tex

sw02:
	pdflatex notes_sw02.tex
	pdflatex notes_sw02.tex
	pdflatex notes_sw02.tex

sw04:
	pdflatex notes_sw04.tex
	pdflatex notes_sw04.tex
	pdflatex notes_sw04.tex

sw05:
	pdflatex notes_sw05.tex
	pdflatex notes_sw05.tex
	pdflatex notes_sw05.tex

sw07:
	pdflatex notes_sw07.tex
	pdflatex notes_sw07.tex
	pdflatex notes_sw07.tex

sw08:
	pdflatex notes_sw08.tex
	pdflatex notes_sw08.tex
	pdflatex notes_sw08.tex

clean:
	rm -f *.aux
	rm -f *.lof
	rm -f *.log
	rm -f *.lol
	rm -f *.lot
	rm -f *.out
	rm -f *.toc
