.PHONY: all build clean

all: build clean

build: sw01 sw02

sw01:
	pdflatex notes_sw01.tex
	pdflatex notes_sw01.tex
	pdflatex notes_sw01.tex

sw02:
	pdflatex notes_sw02.tex
	pdflatex notes_sw02.tex
	pdflatex notes_sw02.tex

clean:
	rm -f *.aux
	rm -f *.lof
	rm -f *.log
	rm -f *.lol
	rm -f *.lot
	rm -f *.out
	rm -f *.toc
